"""AION AXON sandbox service.

The trust boundary. Candidate capabilities generated by SYNAPSE run HERE,
never inside aion-core, because generated code must never sit next to
credentials.

This service is deployed with NO secrets and NO service-account key. It
proves that at startup by scanning its own environment for anything that
looks like a credential and logging the result. The same scan is exposed
at /env-proof so the claim is checkable from outside, not just asserted
in a README.

Phase 2 scope: the boundary and its proof. Candidate execution arrives in
Phase 6.
"""
import logging
import os
from typing import Any

from fastapi import FastAPI

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("aion-sandbox")

# Anything matching these is a credential as far as this service is
# concerned. Deliberately broad: a false positive is a loud startup log,
# a false negative is a security hole.
CREDENTIAL_MARKERS = (
    "KEY",
    "SECRET",
    "TOKEN",
    "PASSWORD",
    "CREDENTIAL",
    "AUTH",
    "PRIVATE",
)

# Set by the platform or the base image, carry no authority, and would
# otherwise show up as false positives.
#
# GPG_KEY is the python:3.11-slim base image's PUBLIC signing key id, used
# to verify the Python tarball. It is a public identifier, not a secret.
# It is listed in the /env-proof response as an ignored variable rather
# than filtered silently: an allowlist a reader cannot see is not a proof.
ALLOWED = {
    "GOOGLE_CLOUD_PROJECT",
    "K_SERVICE",
    "K_REVISION",
    "K_CONFIGURATION",
    "GPG_KEY",
}


def scan_environment() -> list[str]:
    """Return the NAMES of any credential-looking variables.

    Names only. This function must never return or log a value, or the
    proof would itself become the leak.
    """
    found = []

    for name in os.environ:
        if name in ALLOWED:
            continue
        if any(marker in name.upper() for marker in CREDENTIAL_MARKERS):
            found.append(name)

    return sorted(found)


def ignored_variables() -> list[str]:
    """Names matching a credential marker that were deliberately allowed.

    Published alongside the verdict so the allowlist is auditable from
    outside the container.
    """
    return sorted(
        name for name in os.environ
        if name in ALLOWED
        and any(marker in name.upper() for marker in CREDENTIAL_MARKERS)
    )


def env_proof() -> dict[str, Any]:
    found = scan_environment()

    return {
        "service": "aion-sandbox",
        "credentials_found": len(found),
        "credential_variable_names": found,
        "verdict": "ZERO_CREDENTIALS" if not found else "CREDENTIALS_PRESENT",
        "ignored_public_variables": ignored_variables(),
        "service_account_roles": "none granted",
        "trust_boundary": "generated code runs here, secrets do not",
    }


proof = env_proof()

if proof["verdict"] == "ZERO_CREDENTIALS":
    logger.info("SANDBOX ENV PROOF: ZERO_CREDENTIALS - trust boundary intact")
else:
    logger.error(
        "SANDBOX ENV PROOF: CREDENTIALS_PRESENT %s - TRUST BOUNDARY VIOLATED",
        proof["credential_variable_names"],
    )

app = FastAPI(
    title="AION AXON Sandbox",
    description="Isolated execution boundary. Holds no credentials.",
    version="0.2.0",
)


@app.get("/")
def root() -> dict[str, Any]:
    return {"service": "aion-sandbox", "status": "LIVE"}


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "OK"}


@app.get("/env-proof")
def get_env_proof() -> dict[str, Any]:
    # Recomputed per request, not served from the startup cache, so the
    # proof reflects the environment right now.
    return env_proof()
