"""AION AXON sandbox service.

The trust boundary. Candidate capabilities generated by SYNAPSE run HERE,
never inside aion-core, because generated code must never sit next to
credentials.

This service is deployed with NO secrets and NO service-account key. It
proves that at startup by scanning its own environment for anything that
looks like a credential and logging the result. The same scan is exposed
at /env-proof so the claim is checkable from outside, not just asserted
in a README.

Phase 2 scope: the boundary and its proof. Candidate execution arrives in
Phase 6.
"""
import logging
import os
import subprocess
import sys
import tempfile
from typing import Any

try:
    # POSIX only. Absent on the Windows dev machine, always present in the
    # deployed Linux container where the caps actually matter.
    import resource
except ImportError:  # pragma: no cover - Windows dev only
    resource = None

from fastapi import FastAPI
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("aion-sandbox")

# Anything matching these is a credential as far as this service is
# concerned. Deliberately broad: a false positive is a loud startup log,
# a false negative is a security hole.
CREDENTIAL_MARKERS = (
    "KEY",
    "SECRET",
    "TOKEN",
    "PASSWORD",
    "CREDENTIAL",
    "AUTH",
    "PRIVATE",
)

# Set by the platform or the base image, carry no authority, and would
# otherwise show up as false positives.
#
# GPG_KEY is the python:3.11-slim base image's PUBLIC signing key id, used
# to verify the Python tarball. It is a public identifier, not a secret.
# It is listed in the /env-proof response as an ignored variable rather
# than filtered silently: an allowlist a reader cannot see is not a proof.
ALLOWED = {
    "GOOGLE_CLOUD_PROJECT",
    "K_SERVICE",
    "K_REVISION",
    "K_CONFIGURATION",
    "GPG_KEY",
}

MAX_SECONDS = int(os.getenv("SANDBOX_TIMEOUT_SECONDS", "10"))
MAX_MEMORY_BYTES = int(
    os.getenv("SANDBOX_MEMORY_BYTES", str(256 * 1024 * 1024))
)
MAX_OUTPUT_CHARS = 20_000
MAX_CODE_CHARS = 40_000


def scan_environment() -> list[str]:
    """Return the NAMES of any credential-looking variables.

    Names only. This function must never return or log a value, or the
    proof would itself become the leak.
    """
    found = []

    for name in os.environ:
        if name in ALLOWED:
            continue
        if any(marker in name.upper() for marker in CREDENTIAL_MARKERS):
            found.append(name)

    return sorted(found)


def ignored_variables() -> list[str]:
    """Names matching a credential marker that were deliberately allowed.

    Published alongside the verdict so the allowlist is auditable from
    outside the container.
    """
    return sorted(
        name for name in os.environ
        if name in ALLOWED
        and any(marker in name.upper() for marker in CREDENTIAL_MARKERS)
    )


def env_proof() -> dict[str, Any]:
    found = scan_environment()

    return {
        "service": "aion-sandbox",
        "credentials_found": len(found),
        "credential_variable_names": found,
        "verdict": "ZERO_CREDENTIALS" if not found else "CREDENTIALS_PRESENT",
        "ignored_public_variables": ignored_variables(),
        "service_account_roles": "none granted",
        "trust_boundary": "generated code runs here, secrets do not",
    }


proof = env_proof()

if proof["verdict"] == "ZERO_CREDENTIALS":
    logger.info("SANDBOX ENV PROOF: ZERO_CREDENTIALS - trust boundary intact")
else:
    logger.error(
        "SANDBOX ENV PROOF: CREDENTIALS_PRESENT %s - TRUST BOUNDARY VIOLATED",
        proof["credential_variable_names"],
    )

app = FastAPI(
    title="AION AXON Sandbox",
    description="Isolated execution boundary. Holds no credentials.",
    version="0.2.0",
)


@app.get("/")
def root() -> dict[str, Any]:
    return {"service": "aion-sandbox", "status": "LIVE"}


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "OK"}


@app.get("/env-proof")
def get_env_proof() -> dict[str, Any]:
    # Recomputed per request, not served from the startup cache, so the
    # proof reflects the environment right now.
    return env_proof()


class ExecutionRequest(BaseModel):
    code: str = Field(..., description="Candidate capability source.")
    test: str = Field("", description="Test code appended after the source.")
    timeout_seconds: int = Field(MAX_SECONDS, ge=1, le=30)


def _limits() -> None:
    """Resource caps applied inside the child, before the code runs."""
    if resource is None:  # pragma: no cover - Windows dev only
        return

    resource.setrlimit(
        resource.RLIMIT_AS, (MAX_MEMORY_BYTES, MAX_MEMORY_BYTES)
    )
    resource.setrlimit(resource.RLIMIT_CPU, (MAX_SECONDS, MAX_SECONDS))
    resource.setrlimit(resource.RLIMIT_FSIZE, (1024 * 1024, 1024 * 1024))
    # No forking: a candidate must not spawn workers that outlive its cap.
    resource.setrlimit(resource.RLIMIT_NPROC, (0, 0))


@app.post("/execute")
def execute(request: ExecutionRequest) -> dict[str, Any]:
    """Run a candidate capability and report what happened.

    Returns a result for EVERY outcome, including failure. A candidate
    that crashes is a valid and useful answer -- it is exactly what
    stage-2 exists to discover -- and must never read as a sandbox
    outage, or SYNAPSE would retry a genuinely broken candidate forever.

    Safe to expose only because the blast radius is deliberately empty:
    no credentials, no IAM roles, non-root, ephemeral container, stripped
    child environment, and hard CPU / memory / wall-clock / fork caps.
    """
    if len(request.code) > MAX_CODE_CHARS:
        return {
            "status": "REJECTED",
            "passed": False,
            "reason": f"Code exceeds {MAX_CODE_CHARS} characters.",
        }

    source = request.code

    if request.test:
        source = f"{source}\n\n{request.test}\n"

    timeout = min(request.timeout_seconds, MAX_SECONDS)

    with tempfile.TemporaryDirectory() as workdir:
        path = os.path.join(workdir, "candidate.py")

        with open(path, "w", encoding="utf-8") as handle:
            handle.write(source)

        # A stripped environment: the child cannot read what the parent
        # holds, even though the parent holds nothing worth reading.
        child_env = {
            "PATH": "/usr/local/bin:/usr/bin:/bin",
            "HOME": workdir,
            "PYTHONDONTWRITEBYTECODE": "1",
        }

        try:
            completed = subprocess.run(
                [sys.executable, "-I", path],
                cwd=workdir,
                env=child_env,
                capture_output=True,
                text=True,
                timeout=timeout,
                preexec_fn=(
                    _limits if os.name != "nt" and resource else None
                ),
            )
        except subprocess.TimeoutExpired:
            return {
                "status": "TIMEOUT",
                "passed": False,
                "timeout_seconds": timeout,
                "reason": f"Candidate exceeded {timeout}s.",
            }
        except Exception as error:  # noqa: BLE001 - reported, not raised
            return {
                "status": "ERROR",
                "passed": False,
                "reason": f"{type(error).__name__}: {error}",
            }

    return {
        "status": "COMPLETED",
        "passed": completed.returncode == 0,
        "exit_code": completed.returncode,
        "stdout": completed.stdout[:MAX_OUTPUT_CHARS],
        "stderr": completed.stderr[:MAX_OUTPUT_CHARS],
        "timeout_seconds": timeout,
    }
